/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delivery.telas;

import delivery.basica.Produto;
import delivery.negocio.RNProduto;
import delivery.util.CurrencyTableCellRenderer;
import delivery.util.DAOException;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Augusto
 */
public class TelaCadProduto extends javax.swing.JInternalFrame {
    Produto produto;
    
    /**
     * Creates new form TelaCadProduto
     */
    public TelaCadProduto() {
        
        initComponents();
        produto = new Produto();
        lista();
        
               
    }
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeProduto = new javax.swing.JLabel();
        lblValorProduto = new javax.swing.JLabel();
        txtDescricaoProduto = new javax.swing.JTextField();
        lblCadastroProduto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPesquisaProduto = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtValorProduto = new javax.swing.JTextField();
        btnAtualizarProduto = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnRestCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setResizable(true);
        setMinimumSize(new java.awt.Dimension(725, 499));

        lblNomeProduto.setText("Nome do Produto :");

        lblValorProduto.setText("Valor do Produto :");

        lblCadastroProduto.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCadastroProduto.setForeground(new java.awt.Color(0, 51, 204));
        lblCadastroProduto.setText("Cadastro de Produto");

        lblPesquisaProduto.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPesquisaProduto.setForeground(new java.awt.Color(0, 51, 204));
        lblPesquisaProduto.setText("Lista de Produto Cadastrados");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Código", "Nome do Produto", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduto);
        if (tbProduto.getColumnModel().getColumnCount() > 0) {
            tbProduto.getColumnModel().getColumn(0).setMinWidth(50);
            tbProduto.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbProduto.getColumnModel().getColumn(0).setMaxWidth(50);
            tbProduto.getColumnModel().getColumn(2).setMinWidth(80);
            tbProduto.getColumnModel().getColumn(2).setPreferredWidth(80);
            tbProduto.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        btnAlterar.setText("Alterar Produto");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir Produto");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizarProduto.setText("Atualizar Produtos");
        btnAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarProdutoActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnRestCadastro.setText("Resetar Cadastro");
        btnRestCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestCadastroActionPerformed(evt);
            }
        });

        jLabel1.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNomeProduto)
                                    .addComponent(lblValorProduto))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRestCadastro))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAtualizarProduto)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastroProduto)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProduto)
                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorProduto)
                    .addComponent(btnCadastrar)
                    .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestCadastro)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesquisaProduto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnFechar)
                    .addComponent(btnAlterar)
                    .addComponent(btnAtualizarProduto))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        RNProduto rnProd = new RNProduto();
        
        try {
            rnProd.excluir(produto);
            JOptionPane.showMessageDialog(this,"Produto Excluído!");
            lista(); //CHAMADO PARA EVITAR BUG DE ALTERAR PRODUTO NA TABELA QUE NAO FOI ATUALIZADA E CONTEM DADOS ANTIGOS PODENDO CAUSAR PROBLEMAS NO SISTEMA
        } catch (DAOException | SQLException ex) {
            
        }
        
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
      
      RNProduto rnProd = new RNProduto();
      System.out.println(txtValorProduto.getText());
      produto.setDescricao(txtDescricaoProduto.getText().toUpperCase());
      double valor = Double.parseDouble(txtValorProduto.getText().replace(',', '.')); // converte caso tenha virgula em ponto
      produto.setValor(valor);
         
        try {
            rnProd.inserir(produto);
            JOptionPane.showMessageDialog(this,"Produto Cadastrado!");
        } catch (DAOException | SQLException ex) {
            
        }
      
       
          
       
    }//GEN-LAST:event_btnCadastrarActionPerformed
  
    private void tbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutoMouseClicked
       
        
        tbProduto.addMouseListener(new MouseAdapter(){
         private int linha;
            
            @Override  
            public void mouseClicked(MouseEvent e) {  
 
                        linha = tbProduto.getSelectedRow();
                        produto.setCodProduto(Integer.parseInt((String.valueOf(tbProduto.getValueAt(linha, 0)))));  
                        produto.setDescricao(String.valueOf(tbProduto.getValueAt(linha, 1))); 
                        produto.setValor(Double.parseDouble((String.valueOf(tbProduto.getValueAt(linha, 2)))));

                txtDescricaoProduto.setText(produto.getDescricao());
                txtValorProduto.setText(String.valueOf(produto.getValor()));

            }  
        });
    }//GEN-LAST:event_tbProdutoMouseClicked

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        
        dispose();
        
        
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarProdutoActionPerformed
      lista();
      JOptionPane.showMessageDialog(this,"Lista Atualizada!");
    }//GEN-LAST:event_btnAtualizarProdutoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       
        RNProduto rnProd = new RNProduto();
        
        try {
            
            produto.setDescricao(txtDescricaoProduto.getText().toUpperCase());
            double valor = Double.parseDouble(txtValorProduto.getText().replace(',', '.')); // converte caso tenha virgula em ponto
            produto.setValor(valor);
            rnProd.alterar(produto);
            JOptionPane.showMessageDialog(this,"Produto Alterado com Sucesso, Por favor Atualize a Lista!");
        } catch (DAOException | SQLException ex) {
            
        }
        
        
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnRestCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestCadastroActionPerformed
        
       txtDescricaoProduto.setText("");
       txtValorProduto.setText("");
        
        
    }//GEN-LAST:event_btnRestCadastroActionPerformed

     private void lista(){
        RNProduto rnProd = new RNProduto(); //CRIAR A INSTANCIA DA FACHADA
        DefaultTableModel modelo = new DefaultTableModel(); // INSTANCIA O OBJETO PADRÃO DE TABELA - ADICIONE A IMPORTAÇÃO
        ArrayList<Produto> lista = new ArrayList(); // CRIA UMA LISTA, DE ARRAYLIST DE LIVRO
        try {  
            lista = rnProd.listar(); // BUSCA OS DADOS DO BANCO PARA A LISTA
        } catch (Exception ex) {
            
        }
        tbProduto.getColumnModel().getColumn(2).setCellRenderer(new CurrencyTableCellRenderer()); // COLOCA COLUNA VALOR EM REAL
       modelo = (DefaultTableModel) tbProduto.getModel(); // CHECA O JTABLE PARA RECEBER OS DADOS
        if(modelo.getRowCount() > 0){  //se existir linha 
            modelo.setRowCount(0); // apaga todas as linhas
        }
        for (Produto produto : lista) { 
            modelo.addRow(new Object[]{produto.getCodProduto(),produto.getDescricao(),produto.getValor()});
        } // TRAS AS INFORMAÇÕES NA TABELA COM OS DADOS SOLICITADOS.
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtualizarProduto;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRestCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCadastroProduto;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPesquisaProduto;
    private javax.swing.JLabel lblValorProduto;
    private javax.swing.JTable tbProduto;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtValorProduto;
    // End of variables declaration//GEN-END:variables
}
