/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delivery.telas;

import delivery.basica.Cliente;
import delivery.basica.Pedido;
import delivery.basica.Produto;
import delivery.negocio.RNPedido;
import delivery.repositorio.DAOCliente;
import delivery.repositorio.DAOProduto;
import delivery.util.CurrencyTableCellRenderer;
import delivery.util.DAOException;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Augusto
 */
public class TelaAtendimento extends javax.swing.JInternalFrame {

    Pedido pedido;
    Cliente clienteRetorno;
    
    /**
     * CENTRALIZA A TELA NO MENU PRINCIPAL
     */
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    ArrayList<Produto> produto;
    DefaultTableModel modelo;
    DAOProduto daop;

    /**
     * Creates new form TelaAtendimento
     */
    public TelaAtendimento() {
        initComponents();
        pedido = new Pedido();
        clienteRetorno = new Cliente();
        produto =  new ArrayList<>();   
        daop = new DAOProduto();
        InicioComanda();
    }
    
    private void InicioComanda(){
        
        
        tbComanda.getColumnModel().getColumn(2).setCellRenderer(new CurrencyTableCellRenderer());
        tbComanda.getColumnModel().getColumn(4).setCellRenderer(new CurrencyTableCellRenderer());
       modelo = new DefaultTableModel();
       modelo = (DefaultTableModel) tbComanda.getModel();
       if(modelo.getRowCount() >0){
         modelo.setRowCount(0);  
       }
  
    }
    
    
    private void calcular(){
        
        if(!txtTotalPagar.getText().isEmpty() || !txtTotalPagar.getText().trim().equals("")){
                txtTotalPagar.setValue(contadorTotal() +  Double.parseDouble(txtValorFrete.getText().replace(",", ".").replace("R$", "")));
              //  txtTotalPagar.setValue(Double.parseDouble(txtTotalPagar.getText().replace(",", ".").replace("R$", "")) + Double.parseDouble(txtValorFrete.getText().replace(",", ".").replace("R$", "")));
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblEnderecoCliente = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblReferenciaEntrega = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblPedido = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtCodVenda = new javax.swing.JTextField();
        txtNomeProdVenda = new javax.swing.JTextField();
        txtQuntdProdVenda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotalPagar = new javax.swing.JLabel();
        lblValorDinheiro = new javax.swing.JLabel();
        lblTrocoDinheiro = new javax.swing.JLabel();
        btnImprimirPedido = new javax.swing.JButton();
        btnResetGeral = new javax.swing.JButton();
        btnAdicionarProduto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbComanda = new javax.swing.JTable();
        txtReferencia1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnResetCliente = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblDadosdoCliente = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblValorFrete = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JFormattedTextField();
        txtValorProdVenda = new javax.swing.JFormattedTextField();
        txtValorDinheiro = new javax.swing.JFormattedTextField();
        txtValorFrete = new javax.swing.JFormattedTextField();
        txtTrocoDinheiro = new javax.swing.JFormattedTextField();
        txtQtdPedido = new javax.swing.JTextField();
        lblQtdPedido = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkCartao = new java.awt.Checkbox();
        lblStatus = new javax.swing.JLabel();

        lblNomeCliente.setText("Nome do Cliente:");

        txtNomeCliente.setEditable(false);

        lblEnderecoCliente.setText("Endereço do Cliente:");

        txtEndereco.setEditable(false);

        lblReferenciaEntrega.setText("Referência para entrega:");

        txtComplemento.setEditable(false);

        lblPedido.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPedido.setForeground(new java.awt.Color(0, 51, 204));
        lblPedido.setText("Itens de Venda");

        lblCodigo.setText("Código");

        lblNomeProduto.setText("Nome do Produto");

        lblValor.setText("Valor");

        lblQuantidade.setText("Quantidade");

        txtCodVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodVendaFocusLost(evt);
            }
        });
        txtCodVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodVendaActionPerformed(evt);
            }
        });
        txtCodVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodVendaKeyPressed(evt);
            }
        });

        txtNomeProdVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeProdVendaKeyTyped(evt);
            }
        });

        txtQuntdProdVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuntdProdVendaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuntdProdVendaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Produtos da Comanda");

        lblTotalPagar.setText("Valor Total a Pagar:");

        lblValorDinheiro.setText("Valor em Dinheiro:");

        lblTrocoDinheiro.setText("Troco em Dinheiro:");

        btnImprimirPedido.setText("Imprimir Comanda");
        btnImprimirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirPedidoActionPerformed(evt);
            }
        });
        btnImprimirPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnImprimirPedidoKeyPressed(evt);
            }
        });

        btnResetGeral.setText("Limpar todas as Informações");
        btnResetGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetGeralActionPerformed(evt);
            }
        });
        btnResetGeral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnResetGeralKeyPressed(evt);
            }
        });

        btnAdicionarProduto.setText("Adicionar Produto");
        btnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoActionPerformed(evt);
            }
        });
        btnAdicionarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicionarProdutoKeyPressed(evt);
            }
        });

        tbComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome do Produto", "Valor Unitário", "Qtd.", "Total Produto", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbComandaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbComanda);
        if (tbComanda.getColumnModel().getColumnCount() > 0) {
            tbComanda.getColumnModel().getColumn(0).setMinWidth(50);
            tbComanda.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbComanda.getColumnModel().getColumn(0).setMaxWidth(50);
            tbComanda.getColumnModel().getColumn(2).setMinWidth(85);
            tbComanda.getColumnModel().getColumn(2).setPreferredWidth(85);
            tbComanda.getColumnModel().getColumn(2).setMaxWidth(85);
            tbComanda.getColumnModel().getColumn(3).setMinWidth(50);
            tbComanda.getColumnModel().getColumn(3).setPreferredWidth(50);
            tbComanda.getColumnModel().getColumn(3).setMaxWidth(50);
            tbComanda.getColumnModel().getColumn(4).setMinWidth(80);
            tbComanda.getColumnModel().getColumn(4).setPreferredWidth(80);
            tbComanda.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        txtReferencia1.setEditable(false);

        jLabel2.setText("Complemento:");

        lblNumero.setText("Número:");

        txtNumero.setEditable(false);

        btnSair.setText("Encerrar o Atendimento ( Exit )");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        btnSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSairKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnResetCliente.setText("Reset Cliente");
        btnResetCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetClienteActionPerformed(evt);
            }
        });
        btnResetCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnResetClienteKeyPressed(evt);
            }
        });

        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });
        btnLocalizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLocalizarKeyPressed(evt);
            }
        });

        lblTelefone.setText("Telefone:");

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResetCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLocalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetCliente)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblDadosdoCliente.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDadosdoCliente.setForeground(new java.awt.Color(0, 51, 204));
        lblDadosdoCliente.setText("Dados do Cliente");

        lblValorFrete.setText("Valor do Frete:");

        txtTotalPagar.setEditable(false);
        txtTotalPagar.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalPagar.setForeground(new java.awt.Color(255, 0, 51));
        txtTotalPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtTotalPagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtValorProdVenda.setEditable(false);
        txtValorProdVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        txtValorDinheiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtValorDinheiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtValorDinheiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorDinheiroFocusLost(evt);
            }
        });
        txtValorDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorDinheiroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorDinheiroKeyTyped(evt);
            }
        });

        txtValorFrete.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtValorFrete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtValorFrete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFreteFocusLost(evt);
            }
        });
        txtValorFrete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorFreteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorFreteKeyTyped(evt);
            }
        });

        txtTrocoDinheiro.setEditable(false);
        txtTrocoDinheiro.setForeground(new java.awt.Color(0, 153, 51));
        txtTrocoDinheiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtTrocoDinheiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtQtdPedido.setEditable(false);
        txtQtdPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblQtdPedido.setText("Qtd. Pedido:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkCartao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chkCartao.setForeground(new java.awt.Color(0, 51, 204));
        chkCartao.setLabel("Cartão");
        chkCartao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCartaoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(chkCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblStatus.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(381, 381, 381))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTotalPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTrocoDinheiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTrocoDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnResetGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnImprimirPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValorDinheiro)
                                    .addComponent(lblValorFrete))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtValorFrete)
                                    .addComponent(txtValorDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNomeCliente)
                                            .addComponent(jLabel2)
                                            .addComponent(lblEnderecoCliente))
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblReferenciaEntrega)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtComplemento)
                                            .addComponent(txtReferencia1)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtEndereco)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblNumero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblQtdPedido)
                                                .addGap(2, 2, 2)
                                                .addComponent(txtQtdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(25, 25, 25))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(lblDadosdoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeProduto)
                                    .addComponent(txtNomeProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(lblPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblValor)
                                            .addComponent(txtValorProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblQuantidade)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtQuntdProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAdicionarProduto)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDadosdoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeCliente)
                            .addComponent(txtQtdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdPedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnderecoCliente)
                            .addComponent(lblNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReferencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReferenciaEntrega))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPedido)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeProduto)
                            .addComponent(lblCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(lblQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuntdProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionarProduto)
                            .addComponent(txtValorProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorFrete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorDinheiro)
                            .addComponent(txtValorDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalPagar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTrocoDinheiro)
                            .addComponent(txtTrocoDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimirPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetGeral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoActionPerformed
        Produto prod =  new Produto();

        try{
            
            if(txtCodVenda.getText().isEmpty() || txtCodVenda.getText().trim().equals("")){
                throw new DAOException("Codigo em Branco.");
        }else{
            prod.setCodProduto(Integer.parseInt(txtCodVenda.getText()));
        }
         
            
           if(txtNomeProdVenda.getText().isEmpty() || txtNomeProdVenda.getText().trim().equals("")){
                throw new DAOException("Nome do Produto em Branco.");              
        }else{
            prod.setDescricao(txtNomeProdVenda.getText());
        } 
            
           if(txtValorProdVenda.getText().isEmpty() || txtValorProdVenda.getText().trim().equals("")){
                throw new DAOException("Erro campo valor Invalido.");
        }else{
            prod.setValor(Double.parseDouble(txtValorProdVenda.getValue().toString()));
        }
           
           if(!txtQuntdProdVenda.getText().matches("^[0-9]*$")){
               throw new DAOException("Erro Digite Somente Numeros na Quantidade.");
           }
                   
           if(txtQuntdProdVenda.getText().isEmpty() || txtValorProdVenda.getText().trim().equals("")){
            prod.setUnidade(1);
        }else{
            prod.setUnidade(Integer.parseInt(txtQuntdProdVenda.getText())); 
        }
                     
           modelo.addRow(new Object[]{prod.getCodProduto(),
                    prod.getDescricao(),
                    prod.getValor(),
                    prod.getUnidade(),
                    (prod.getValor()*prod.getUnidade())
                        
                });
               
                
                txtCodVenda.setText("");
                txtNomeProdVenda.setText("");
                txtValorProdVenda.setText("");
                txtQuntdProdVenda.setText("");
                txtCodVenda.grabFocus();
                
                 contadorTotal();
            
        } catch (DAOException ex) {
            
        }
             
    }//GEN-LAST:event_btnAdicionarProdutoActionPerformed

    private double contadorTotal(){
       
        int m = modelo.getRowCount();
        double valorTotal = 0;
        for(int c=0;c < m;c++){
            
            valorTotal += Double.parseDouble(modelo.getValueAt(c, 4).toString());
            txtTotalPagar.setValue(valorTotal);
        }
        return valorTotal;
    }
    
    
    
    public void AtualizarTroco(){
        
        if(!chkCartao.getState()){
            
            if(!txtValorDinheiro.getText().isEmpty() || !txtValorDinheiro.getText().trim().equals("")){
            double v1 = Double.parseDouble(txtValorDinheiro.getText().replace(",", ".").replace("R$",""));
        double v2 = Double.parseDouble(txtTotalPagar.getText().replace(",", ".").replace("R$", ""));
        
        if( v1 <= v2){
            txtTrocoDinheiro.setValue(0);
        }else{
          txtTrocoDinheiro.setValue(v1 - v2);  
        }
        }        
        
            
        }
        
    }
    
    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed

        DAOCliente daoc = new DAOCliente();
        Cliente nvc = new Cliente();
        
        nvc.setTelefone(txtTelefone.getText());
        
        try {
            clienteRetorno = daoc.consultarTelefone(nvc);
            
            if(clienteRetorno != null ){
                
                txtNomeCliente.setText(clienteRetorno.getNome());
                txtEndereco.setText(clienteRetorno.getLogradouro());
                txtComplemento.setText(clienteRetorno.getComplemento());
                txtReferencia1.setText(clienteRetorno.getReferencia());
                txtNumero.setText(clienteRetorno.getNumero());
                txtQtdPedido.setText(String.valueOf(daoc.QtdPedidoCliente(nvc)));
                txtCodVenda.grabFocus();
                
            }else{
                txtTelefone.grabFocus();
                txtTelefone.setText("");
                throw new DAOException("Cliente não cadastrado.");    
            }
            
            
            // TODO add your handling code here:
        } catch (DAOException | SQLException ex) {
            
        }
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        dispose();
        
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnResetClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetClienteActionPerformed
        
        txtTelefone.setText("");
        txtNomeCliente.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtReferencia1.setText("");
        txtComplemento.setText("");
        txtTelefone.grabFocus();
        
        
        
    }//GEN-LAST:event_btnResetClienteActionPerformed

    private void txtCodVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodVendaFocusLost

        Produto produto = new Produto();
        Produto p;
        
        
        if(!txtCodVenda.getText().trim().isEmpty() || !txtCodVenda.getText().equalsIgnoreCase("")){
        produto.setCodProduto(Integer.parseInt(txtCodVenda.getText()));
        }else{
          txtNomeProdVenda.setEditable(true);
          txtNomeProdVenda.setText("");
          txtValorProdVenda.setText("");
        }
        
        try {
            p = daop.PesqProdCodigo(produto);
            
            if(p != null){
               
            txtCodVenda.setText(String.valueOf(p.getCodProduto()));
            txtNomeProdVenda.setText(p.getDescricao());
            txtValorProdVenda.setValue(p.getValor());
            txtNomeProdVenda.setEditable(false);
            txtQuntdProdVenda.grabFocus();
            
            }

             } catch (DAOException | SQLException ex) {
            
        }
  
    }//GEN-LAST:event_txtCodVendaFocusLost

    private void txtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnLocalizar.grabFocus();
        }
        
        
    }//GEN-LAST:event_txtTelefoneKeyPressed

    private void btnLocalizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLocalizarKeyPressed
        
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnLocalizar.doClick();
        } 
        
        
    }//GEN-LAST:event_btnLocalizarKeyPressed

    private void btnResetClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnResetClienteKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnResetCliente.doClick();
        }
        
    }//GEN-LAST:event_btnResetClienteKeyPressed

    private void btnAdicionarProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnAdicionarProduto.doClick();
        }
        
    }//GEN-LAST:event_btnAdicionarProdutoKeyPressed

    private void btnImprimirPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnImprimirPedidoKeyPressed
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnImprimirPedido.doClick();
        }
        
        
    }//GEN-LAST:event_btnImprimirPedidoKeyPressed

    private void btnResetGeralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnResetGeralKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnResetGeral.doClick();
        }
        
        
    }//GEN-LAST:event_btnResetGeralKeyPressed

    private void btnSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSairKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnSair.doClick();
        }
    }//GEN-LAST:event_btnSairKeyPressed

    private void txtCodVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodVendaKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtNomeProdVenda.grabFocus();
        }
    }//GEN-LAST:event_txtCodVendaKeyPressed

    private void txtCodVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodVendaActionPerformed
       
   
    }//GEN-LAST:event_txtCodVendaActionPerformed

    private void txtQuntdProdVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuntdProdVendaKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnAdicionarProduto.grabFocus();
        }
        
    }//GEN-LAST:event_txtQuntdProdVendaKeyPressed

    private void btnResetGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetGeralActionPerformed
        
        modelo.setRowCount(0);
        txtTotalPagar.setText("");
        txtCodVenda.setText("");
        txtNomeProdVenda.setText("");
        txtValorProdVenda.setText("");
        txtQuntdProdVenda.setText(""); 
        txtTrocoDinheiro.setText("");
        txtValorDinheiro.setText("");
        txtValorFrete.setText("");
        
        
    }//GEN-LAST:event_btnResetGeralActionPerformed

    private void txtValorDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDinheiroKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB){
           AtualizarTroco(); 
           btnImprimirPedido.grabFocus();
        }
    }//GEN-LAST:event_txtValorDinheiroKeyPressed

    private void tbComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbComandaMouseClicked
        Produto pro = new Produto();
        if(evt.getClickCount() == 2 ){
            
            tbComanda.addMouseListener(new MouseAdapter(){
                
          private int linha;
            
            @Override  
            public void mouseClicked(MouseEvent e) {    
 
                        linha = tbComanda.getSelectedRow();
                        pro.setCodProduto(Integer.parseInt(tbComanda.getValueAt(linha,0).toString()));
                        pro.setDescricao(tbComanda.getValueAt(linha, 1).toString());
                        pro.setUnidade(Integer.parseInt(tbComanda.getValueAt(linha, 3).toString()));
                        pro.setValor(Double.parseDouble(tbComanda.getValueAt(linha, 2).toString()));
                        if(tbComanda.getValueAt(linha, 5) != null){
                           pro.setObsProduto(tbComanda.getValueAt(linha, 5).toString()); 
                        }
                        
           TelaAlterarProdutoPedido alterarProduto = new TelaAlterarProdutoPedido(pro);
           alterarProduto.setModal(true);
           alterarProduto.setLocationRelativeTo(null);

           alterarProduto.setVisible(true);
           
           Produto retorno = new Produto();
           retorno = alterarProduto.retornoProduto();
           
           if(retorno != null){
               tbComanda.setValueAt(retorno.getUnidade(), linha, 3);
               tbComanda.setValueAt(retorno.getValor()*retorno.getUnidade(), linha, 4);
               tbComanda.setValueAt(retorno.getObsProduto(), linha, 5);
               contadorTotal();
               AtualizarTroco();
           }           

            }  
          
            });
        }
        
        
    }//GEN-LAST:event_tbComandaMouseClicked

    private void txtValorDinheiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorDinheiroFocusLost
        double valor;
        if(!txtValorDinheiro.getText().isEmpty() || !txtValorDinheiro.getText().trim().equals("")){
        valor = Double.parseDouble(txtValorDinheiro.getText().replace(",", ".").replace("R$",""));
        txtValorDinheiro.setValue(valor);
        AtualizarTroco();
        }
        
    }//GEN-LAST:event_txtValorDinheiroFocusLost

    private void txtValorFreteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFreteFocusLost
        double valor;
        if(!txtValorFrete.getText().isEmpty() || !txtValorFrete.getText().trim().equals("")){
            valor = Double.parseDouble(txtValorFrete.getText().replace(",", ".").replace("R$",""));
            txtValorFrete.setValue(valor);
            calcular();
            AtualizarTroco();
        }
        
        
    }//GEN-LAST:event_txtValorFreteFocusLost

    private void txtValorFreteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorFreteKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB){
            txtValorDinheiro.grabFocus();
        }
    }//GEN-LAST:event_txtValorFreteKeyPressed

    private void txtValorFreteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorFreteKeyTyped
       String carac = "0123456789,.";
        if(!carac.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtValorFreteKeyTyped

    private void txtValorDinheiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDinheiroKeyTyped
        String carac = "0123456789,.";
        if(!carac.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtValorDinheiroKeyTyped

    private void txtQuntdProdVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuntdProdVendaKeyTyped
        String carac = "0123456789";
        if(!carac.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_txtQuntdProdVendaKeyTyped

    private void txtNomeProdVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdVendaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdVendaKeyTyped

    private void chkCartaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCartaoItemStateChanged
        if(chkCartao.getState()){
            txtValorDinheiro.setText("");
            pedido.setPgto("C");
            txtValorDinheiro.setEditable(false);
            AtualizarTroco();
        }else{
            pedido.setPgto("D");
            txtValorDinheiro.setEditable(true);
            AtualizarTroco();
        }
        
        
    }//GEN-LAST:event_chkCartaoItemStateChanged

    private void btnImprimirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirPedidoActionPerformed
            RNPedido rn = new RNPedido();
            int codigo = 0;
            lblStatus.setText("Gravando Pedido...");
            pedido.setCliente(clienteRetorno);
             if(!chkCartao.getState()){
                 pedido.setPgto("D");   
                }
           
           if(txtValorFrete.getValue() == null){
               pedido.setValorFrete(0);
           }else{
               pedido.setValorFrete(Double.parseDouble(txtValorFrete.getValue().toString()));
           }
           pedido.setValorTotal(Double.parseDouble(txtTotalPagar.getValue().toString()));
           
           //int linha = 0;
           
           ArrayList<Produto> produtos = new ArrayList<>();
           
          
           //while(linha < modelo.getRowCount()){
               for(int linha = 0; linha < modelo.getRowCount();linha++){
                    Produto p = new Produto();
                    p.setCodProduto(Integer.parseInt(modelo.getValueAt(linha, 0).toString()));
                    p.setDescricao(modelo.getValueAt(linha, 1).toString());
                    p.setValor(Double.parseDouble(modelo.getValueAt(linha, 2).toString()));
                    p.setUnidade(Integer.parseInt(modelo.getValueAt(linha, 3).toString()));
                    if(modelo.getValueAt(linha, 5) != null){
                    p.setObsProduto(modelo.getValueAt(linha, 5).toString());   
                    }
                    produtos.add(p);
                } 
           
           pedido.setProduto(produtos);
           try{
               if(clienteRetorno != null){
               codigo = rn.inserir(pedido);    
               }
               
               lblStatus.setText("Número do Pedido: "+ codigo+" Registrado com Sucesso.");
               
           } catch (DAOException | SQLException ex) {
            
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnImprimirPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnImprimirPedido;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnResetCliente;
    private javax.swing.JButton btnResetGeral;
    private javax.swing.JButton btnSair;
    private java.awt.Checkbox chkCartao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDadosdoCliente;
    private javax.swing.JLabel lblEnderecoCliente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblQtdPedido;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblReferenciaEntrega;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JLabel lblTrocoDinheiro;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorDinheiro;
    private javax.swing.JLabel lblValorFrete;
    private javax.swing.JTable tbComanda;
    private javax.swing.JTextField txtCodVenda;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeProdVenda;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtQtdPedido;
    private javax.swing.JTextField txtQuntdProdVenda;
    private javax.swing.JTextField txtReferencia1;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JFormattedTextField txtTotalPagar;
    private javax.swing.JFormattedTextField txtTrocoDinheiro;
    private javax.swing.JFormattedTextField txtValorDinheiro;
    private javax.swing.JFormattedTextField txtValorFrete;
    private javax.swing.JFormattedTextField txtValorProdVenda;
    // End of variables declaration//GEN-END:variables
}
