/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delivery.telas;

import delivery.basica.Cliente;
import delivery.basica.Produto;
import delivery.repositorio.DAOCliente;
import delivery.repositorio.DAOProduto;
import delivery.util.DAOException;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rafael Augusto
 */
public class TelaAtendimento extends javax.swing.JInternalFrame {

    /**
     * CENTRALIZA A TELA NO MENU PRINCIPAL
     */
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * Creates new form TelaAtendimento
     */
    public TelaAtendimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblEnderecoCliente = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblReferenciaEntrega = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblPedido = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblObservacaoCliente = new javax.swing.JLabel();
        txtCodVenda = new javax.swing.JTextField();
        txtNomeProdVenda = new javax.swing.JTextField();
        txtValorProdVenda = new javax.swing.JTextField();
        txtQuntdProdVenda = new javax.swing.JTextField();
        txtObservacaoVenda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblTotalPagar = new javax.swing.JLabel();
        lblValorDinheiro = new javax.swing.JLabel();
        lblTrocoDinheiro = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        txtValorDinheiro = new javax.swing.JTextField();
        txtTrocoDinheiro = new javax.swing.JTextField();
        btnImprimirPedido = new javax.swing.JButton();
        btnResetGeral = new javax.swing.JButton();
        btnAdicionarProduto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtReferencia1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnResetCliente = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblDadosdoCliente = new javax.swing.JLabel();

        lblNomeCliente.setText("Nome do Cliente:");

        txtNomeCliente.setEditable(false);

        lblEnderecoCliente.setText("Endereço do Cliente:");

        txtEndereco.setEditable(false);

        lblReferenciaEntrega.setText("Referência para entrega:");

        txtComplemento.setEditable(false);

        lblPedido.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPedido.setForeground(new java.awt.Color(0, 51, 204));
        lblPedido.setText("Itens de Venda");

        lblCodigo.setText("Código");

        lblNomeProduto.setText("Nome do Produto");

        lblValor.setText("Valor");

        lblQuantidade.setText("Quantidade");

        lblObservacaoCliente.setText("Observação Cliente");

        txtCodVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodVendaFocusLost(evt);
            }
        });
        txtCodVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodVendaKeyPressed(evt);
            }
        });

        txtValorProdVenda.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Comanda");

        lblTotalPagar.setText("Valor total a pagar:");

        lblValorDinheiro.setText("Valor em Dinheiro:");

        lblTrocoDinheiro.setText("Troco em Dinheiro:");

        txtTotalPagar.setEditable(false);

        btnImprimirPedido.setText("Imprimir Pedido");
        btnImprimirPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnImprimirPedidoKeyPressed(evt);
            }
        });

        btnResetGeral.setText("Limpar todas as Informações");
        btnResetGeral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnResetGeralKeyPressed(evt);
            }
        });

        btnAdicionarProduto.setText("Adicionar Produto");
        btnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoActionPerformed(evt);
            }
        });
        btnAdicionarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicionarProdutoKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        txtReferencia1.setEditable(false);

        jLabel2.setText("Complemento:");

        lblNumero.setText("Número:");

        txtNumero.setEditable(false);

        btnSair.setText("Encerrar o Atendimento ( Exit )");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        btnSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSairKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnResetCliente.setText("Reset Cliente");
        btnResetCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetClienteActionPerformed(evt);
            }
        });
        btnResetCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnResetClienteKeyPressed(evt);
            }
        });

        btnLocalizar.setText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });
        btnLocalizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLocalizarKeyPressed(evt);
            }
        });

        lblTelefone.setText("Telefone:");

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResetCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLocalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetCliente)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblDadosdoCliente.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDadosdoCliente.setForeground(new java.awt.Color(0, 51, 204));
        lblDadosdoCliente.setText("Dados do Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblValor)
                                .addGap(39, 39, 39))
                            .addComponent(txtValorProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuantidade)
                            .addComponent(txtQuntdProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblObservacaoCliente))
                            .addComponent(txtObservacaoVenda))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionarProduto)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(397, 397, 397)
                                .addComponent(lblPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNomeCliente)
                                    .addComponent(jLabel2)
                                    .addComponent(lblEnderecoCliente))
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblReferenciaEntrega)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEndereco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                                    .addComponent(txtReferencia1))
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDadosdoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResetGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimirPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblValorDinheiro, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTotalPagar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTrocoDinheiro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalPagar)
                            .addComponent(txtValorDinheiro)
                            .addComponent(txtTrocoDinheiro))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDadosdoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnderecoCliente)
                            .addComponent(lblNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReferencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReferenciaEntrega))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeProduto)
                            .addComponent(lblValor)
                            .addComponent(lblQuantidade)
                            .addComponent(lblCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuntdProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblObservacaoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtObservacaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionarProduto))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPagar)
                            .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorDinheiro))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTrocoDinheiro)
                            .addComponent(txtTrocoDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImprimirPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetGeral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarProdutoActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed

        DAOCliente daoc = new DAOCliente();
        Cliente nvc = new Cliente();
        Cliente retorno;
        nvc.setTelefone(txtTelefone.getText());
        
        try {
            retorno = daoc.consultarTelefone(nvc);
            
            if(retorno != null ){
                
                txtNomeCliente.setText(retorno.getNome());
                txtEndereco.setText(retorno.getLogradouro());
                txtComplemento.setText(retorno.getComplemento());
                txtReferencia1.setText(retorno.getReferencia());
                txtNumero.setText(retorno.getNumero());
                
            }else{
                txtTelefone.grabFocus();
                txtTelefone.setText("");
                throw new DAOException("Cliente não cadastrado.");    
            }
            
            
            // TODO add your handling code here:
        } catch (DAOException | SQLException ex) {
            
        }
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        dispose();
        
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnResetClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetClienteActionPerformed
        
        txtTelefone.setText("");
        txtNomeCliente.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtReferencia1.setText("");
        txtComplemento.setText("");
        txtTelefone.grabFocus();
        
        
        
    }//GEN-LAST:event_btnResetClienteActionPerformed

    private void txtCodVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodVendaFocusLost

        Produto produto = new Produto();
        Produto p;
        DAOProduto daop = new DAOProduto();
        
        if(!txtCodVenda.getText().trim().isEmpty() || !txtCodVenda.getText().equalsIgnoreCase("")){
        produto.setCodProduto(Integer.parseInt(txtCodVenda.getText()));
        }else{
          txtNomeProdVenda.setEditable(true);
          txtNomeProdVenda.setText("");
          txtValorProdVenda.setText("");
        }
        
        try {
            p = daop.PesqProdCodigo(produto);
            
            if(p != null){
               
            txtCodVenda.setText(String.valueOf(p.getCodProduto()));
            txtNomeProdVenda.setText(p.getDescricao());
            txtValorProdVenda.setText(String.valueOf(p.getValor()));
            txtNomeProdVenda.setEditable(false);
            txtQuntdProdVenda.grabFocus();
            
            }
            
            
            
            
             } catch (DAOException | SQLException ex) {
            
        }
  
    }//GEN-LAST:event_txtCodVendaFocusLost

    private void txtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnLocalizar.grabFocus();
        }
        
        
    }//GEN-LAST:event_txtTelefoneKeyPressed

    private void btnLocalizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLocalizarKeyPressed
        
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnLocalizar.doClick();
        } 
        
        
    }//GEN-LAST:event_btnLocalizarKeyPressed

    private void btnResetClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnResetClienteKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnResetCliente.doClick();
        }
        
    }//GEN-LAST:event_btnResetClienteKeyPressed

    private void btnAdicionarProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnAdicionarProduto.doClick();
        }
        
    }//GEN-LAST:event_btnAdicionarProdutoKeyPressed

    private void btnImprimirPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnImprimirPedidoKeyPressed
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnImprimirPedido.doClick();
        }
        
        
    }//GEN-LAST:event_btnImprimirPedidoKeyPressed

    private void btnResetGeralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnResetGeralKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnResetGeral.doClick();
        }
        
        
    }//GEN-LAST:event_btnResetGeralKeyPressed

    private void btnSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSairKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnSair.doClick();
        }
    }//GEN-LAST:event_btnSairKeyPressed

    private void txtCodVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodVendaKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtNomeProdVenda.grabFocus();
        }
    }//GEN-LAST:event_txtCodVendaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnImprimirPedido;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnResetCliente;
    private javax.swing.JButton btnResetGeral;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDadosdoCliente;
    private javax.swing.JLabel lblEnderecoCliente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObservacaoCliente;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblReferenciaEntrega;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JLabel lblTrocoDinheiro;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorDinheiro;
    private javax.swing.JTextField txtCodVenda;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeProdVenda;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtObservacaoVenda;
    private javax.swing.JTextField txtQuntdProdVenda;
    private javax.swing.JTextField txtReferencia1;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTotalPagar;
    private javax.swing.JTextField txtTrocoDinheiro;
    private javax.swing.JTextField txtValorDinheiro;
    private javax.swing.JTextField txtValorProdVenda;
    // End of variables declaration//GEN-END:variables
}
